### PR TITLE
Adding mutation testing to build gradle with PiTest

### PR DESCRIPTION
**Pull request by MitchellGale-BitQuill**
### Description
Adds [PiTest](https://pitest.org/) Gradle to build.gradle in core. This adds support for [Mutation testng/Analysis](https://en.wikipedia.org/wiki/Mutation_testing) to our testing ability. It should help us make more effective tests for past/future features. 

### Why does this help?
Mutation testing is used to find missing parts of your project not covered by existing tests. It modifies (mutates) one part of code and checks if a test is killed (fails) because of the mutation. Sometimes it will make return statements return null, other times it will switch `==` to `!=`, or `<` with `>`, or `||` with `&&` and lots more mutations. More mutations can be found in the `default mutations` column here [https://pitest.org/quickstart/mutators/](https://pitest.org/quickstart/mutators/). Often mutation testing provides a more clear picture of the quality of tests compared to line/branch coverage alone.

If you notice mutations that "survive" your test suite, consider adding additional tests to kill the mutations. 
Short presentation PDF on mutation testing [MutationTesting_Presentation.pdf](https://github.com/Bit-Quill/opensearch-project-sql/files/10081683/MutationTesting_Presentation.pdf).

[Docs for Gradle plugin for PiTest.
](https://gradle-pitest-plugin.solidsoft.info/)

Currently to be manually run, but could be added to GitHub actions later. It generates an html page indicating mutations that survived and were killed by our test suite. 

Only adding support for running mutation testing in core module.
 
### Steps to run
`./gradlew pitest`

Report will be placed in `core/build/reports/pitest/index.html`.

### Sample Report
[PiTest_Results.zip](https://github.com/Bit-Quill/opensearch-project-sql/files/10044940/PiTest_Results.zip)
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yury-Fridlyand** [comment]
Do you have a report example? How can I run the task?

**Comment by MitchellGale-BitQuill** [comment]
```
Do you have a report example? How can I run the task?

```
@Yury-Fridlyand I updated the description to include that info.

[PiTest_Results.zip](https://github.com/Bit-Quill/opensearch-project-sql/files/10044940/PiTest_Results.zip)

**Comment by Yury-Fridlyand** [comment]
When you will publish to upstream, please consider to add
- pitest doc links
- A failure analysis, which describes what
  - is `killed`
  - is `survived`
  - is missing to make test pass
- You can also include your PiTest presentation slides if they don't include confidential information

**Review by Yury-Fridlyand — APPROVED** [review]

**Review by MaxKsyunz — COMMENTED** [review]
Looks really cool @MitchellGale-BitQuill!

Can I run `pittest` in other modules besides `:core`?

As a developer, why would I used it? After I do, what would my next steps be?

**Comment by acarbonetto** [comment]
Would it be worth opening a discussion with the amazon guys for this PR and demo it to them?

**Review by acarbonetto — APPROVED** [review]

**Review by margarit-h — APPROVED** [review]

**Review by GumpacG — APPROVED** [review]

**Review by forestmvey — APPROVED** [review]

**Comment by MitchellGale-BitQuill** [comment]
@MaxKsyunz I just edited the description to answer your question :). But currently it is only added to core, I can certainly add it to additional (or all, but aI think all would be overkill) modules.
Also added more information about rational for adding it.

@acarbonetto Perhaps, could be good to get feedback. Also could be done if they have any questions after seeing the upstream PR.

@Yury-Fridlyand Added link to docs for PiTest. Added presentation slides :). Added more details on features of PiTest, would be happy to discuss adding more if there is anything else I can improve!

Thanks all for feedback.

**Pull request merged**
